<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height


        Carousel:
            direction: "right"
            Label:       
                text: "hello"
                font_size: 32
            Label:       
                text: "hello1"
                font_size: 32
            Label:       
                text: "hello2"
                font_size: 32